// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwu-uVaukj7ZLUhf88FR6h2-RqgUFm38',
    appId: '1:54128513360:web:228423776aa1ce3492dc55',
    messagingSenderId: '54128513360',
    projectId: 'toolstock-30c04',
    authDomain: 'toolstock-30c04.firebaseapp.com',
    storageBucket: 'toolstock-30c04.firebasestorage.app',
    measurementId: 'G-3MQ8SJWH48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9EmP-7s9VJWYnO6KdjQNH6qqqmQjYGY',
    appId: '1:54128513360:android:b5e87f104d54999992dc55',
    messagingSenderId: '54128513360',
    projectId: 'toolstock-30c04',
    storageBucket: 'toolstock-30c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi65D2uspl2EmyrfDI-ZVzgBvLNPpl5kM',
    appId: '1:54128513360:ios:50012e36ac51069492dc55',
    messagingSenderId: '54128513360',
    projectId: 'toolstock-30c04',
    storageBucket: 'toolstock-30c04.firebasestorage.app',
    iosBundleId: 'com.example.toolstockvillalongja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi65D2uspl2EmyrfDI-ZVzgBvLNPpl5kM',
    appId: '1:54128513360:ios:50012e36ac51069492dc55',
    messagingSenderId: '54128513360',
    projectId: 'toolstock-30c04',
    storageBucket: 'toolstock-30c04.firebasestorage.app',
    iosBundleId: 'com.example.toolstockvillalongja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKwu-uVaukj7ZLUhf88FR6h2-RqgUFm38',
    appId: '1:54128513360:web:d0df7a576c24b70992dc55',
    messagingSenderId: '54128513360',
    projectId: 'toolstock-30c04',
    authDomain: 'toolstock-30c04.firebaseapp.com',
    storageBucket: 'toolstock-30c04.firebasestorage.app',
    measurementId: 'G-DDJNXBLXD5',
  );
}
